version: '3'

services:
  db:
    container_name: springbot-pessoal
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - "4141:5432"
    environment:
      - POSTGRESQL_USERNAME=weslin-pessoal
      - POSTGRESQL_PASSWORD=weslin-pessoal
      - POSTGRESQL_DATABASE=userapidb